eslint.config.js

chore React의 no-unused-vars 규칙 비활성화

---

src/index.css

[UI] body에 margin, padding 제거

---

src/App.jsx
src/components/common/bottomNavBar/BottomNavBar.jsx
src/components/common/bottomNavBar/FontAwesome.jsx
src/components/common/bottomNavBar/PlusModal.jsx
src/main.jsx

close #4 
하단 내비바 추가
- 더보기 버튼 클릭 시 모달창 open / close 기능 구현
- 모달창 open 상태에서 모달창을 제외한 부분 클릭 시 모달창 close 기능 구현

[UI] 하단 내비바 추가

---

src/App.jsx
src/components/mainpage/LiveIndexChart.jsx
src/components/mainpage/LiveSearchRank.jsx
src/components/mainpage/MainPortfolio.jsx
src/pages/mainpage/MainPage.jsx
src/pages/portfolioPages/PortfolioMainPage.jsx

close #15 
메인페이지 제작하기
- 검색 엔진 추가
- 실시간 지수 차트 div 추가
- 대표 포트폴리오 div 추가
- 하단 메뉴바 추가
각 컴포넌트 위치 및 크기 확인 한번 해주세요!

[UI] 메인페이지 제작하기

---

src/components/common/BackButton.jsx

1. 뒤로가기 버튼 기능 크기 조정 가능하게 바꿨습니다.
2. 뒤로가기 버튼 기능 경로 지정 가능하게 바꿨습니다.

[FEAT] 뒤로가기 크기 조정 가능, 경로 지정 가능

---

src/components/tickoPages/common/header/CharacterProfile.jsx
src/components/tickoPages/common/header/Header.jsx
src/components/tickoPages/tickoPage/ButtonMenu.jsx
src/components/tickoPages/tickoPage/CharIntroduce.jsx
src/pages/tickoPages/TickoPage.jsx

close #22
- 메인 페이지 제작
- 공통 컴포넌트인 헤더 컴포넌트 제작

[UI] 티코 메인 페이지 제작

---

src/components/common/bottomNavBars/BottomNavBar.jsx

close #25 
변경 전
: 하단 내브바가 bottom에서 띄워져 있어 스크롤이 가능한 페이지에선 화면 내용이 내브바 밑으로 보이는 문제점이 있었음
변경 후
: 하단 내브바 bottom: 0으로 고정 => 화면 내용이 보이는 문제점 해결

[FIX] 하단 내브바 크기 수정

---

src/components/information/CompanyInfo.jsx
src/components/information/NavBtn.jsx
src/components/information/Navigation.jsx
src/pages/InformationPages/Chart.jsx
src/pages/InformationPages/InformationPage.jsx

close #30 
정보제공 페이지의 기업 로고, 기업 이름, 종목 코드, 현재 가격과 변화량 컴포넌트 제작
InformationPage.jsx 파일의 chartData에 데이터를 삽입하면 바로 출력이 되도록 설정하였음.
정보제공 페이지의 하위 컴포넌트(/chart, /finance 등등) 라우팅 설정 수정
기존의 정보제공 페이지(/information) 에서 차트 메뉴 클릭 시 /information/chart 가 아니라 /chart 로 이동하는 문제가 있었음. 이를 /information/chart 로 올바르게 이동하도록 라우팅 수정하였음

[UI] 정보제공 페이지(기업 로고, 이름, 종목 코드, 현재 가격과 변화량 컴포넌트) 추가 및 라우팅 설정 수정

---

src/components/common/bottomNavBars/PlusModal.jsx

모달창이 하단 내브바에서 띄워져 있어 해당 사항 수정하였습니다.

[FIX] 모달창 위치 수정

---

src/components/common/BookMark.jsx

[UI] 북마크 높이, 넓이 조정 가능

---

src/components/tickoPages/BasicWordPage/WordBody.jsx
src/components/tickoPages/BasicWordPage/WordRouting.jsx
src/components/tickoPages/common/SpeechBubble/ElseSpeechBubble.jsx
src/components/tickoPages/common/SpeechBubble/SpeechBubble.jsx
src/components/tickoPages/common/SpeechBubble/StartSpeechBubble.jsx
src/components/tickoPages/common/header/Header.jsx
src/components/tickoPages/common/menu/LinkButton.jsx
src/components/tickoPages/common/menu/Menu.jsx
src/components/tickoPages/tickoPage/ButtonMenu.jsx
src/pages/tickoPages/BasicWordPage.jsx
src/pages/tickoPages/TickoRouting.jsx

close #34 
기초 지식 설명 페이지 ui 제작
- tickopage에서 주식 기초 지식 메뉴 클릭 시 해당 페이지로 이동 기능 구현
- 기초 지식 설명 페이지의 각 메뉴 버튼 클릭 시 해당 설명 페이지로 이동 기능 구현
- 뒤로 가기 버튼 클릭 시 tickopage로 이동 기능 구현

[UI] 기초 지식 설명 페이지 제작

---

src/App.jsx

App.jsx mypage import가 mainpage로 되어있어 오류가 나서 수정했습니다.

[FIX] import 오류 수정

---

src/components/common/BookMark.jsx
src/components/common/NewsCard.jsx

close #37 
1. 공용 컴포넌트인 뉴스 카드 제작
2. 초기 북마크 상태 처리 개선

[UI] 공용 컴포넌트 뉴스 카드 제작

---

src/components/information/CompanyList.jsx

close #35
기업 로고와 기업 이름, 관심 목록이 들어간 컴포넌트를 제작함. 관심 목록의 경우 클릭할 때마다 별 표시가 바뀜.

[UI] 기업 목록 컴포넌트 추가

---

src/App.jsx
src/components/common/NewsCard.jsx
src/components/common/Star.jsx
src/pages/myPages/MyPage.jsx
src/pages/myPages/ScrapNews.jsx

close #46 
1. 스크랩한 뉴스 페이지 제작
2. 스크랩한 뉴스 페이지 경로 추가
3. 약간의 구조 개선

[UI] 스크랩한 뉴스 페이지 제작

---

src/App.jsx
src/components/common/NewsCard.jsx
src/components/information/CompanyList.jsx
src/pages/myPages/FavoriteCompanies.jsx
src/pages/myPages/MyPage.jsx

close #52 
1. 관심 기업 목록 페이지 제작
2. 관심 기업 목록 페이지 경로 추가
3. 콘솔 경고 해결을 위한 코드 수정
4. Star에 props 추가

[UI] 관심 기업 목록 페이지 제작

---

src/pages/loginPage/LoginPage.jsx
src/routes/TotalRoutes.jsx
src/routes/loginPage/LoginRoutes.jsx

close #77 
1. 로그인 페이지 제작
2. 로그인 라우터 추가

[UI] 로그인 페이지 제작

---

src/components/myPages/MyPageModal.jsx

[FEAT] 모달 내려가는 애니메이션 추가

---

src/pages/loginPage/LoginPage.jsx

[REFACTOR] 로그인 기능 추가

---

src/pages/joinPage/JoinPage.jsx
src/pages/loginPage/LoginPage.jsx
src/routes/TotalRoutes.jsx

1. 회원가입 기능 추가
2. 회원가입 라우터 오류 수정
3. 로그인 유저 아이디 변수 이름 변경

[FEAT] 회원가입 기능 추가

---

src/components/common/bottomNavBars/BottomNavBar.jsx
src/components/startPage/ExPageForm.jsx
src/components/startPage/Instruction.jsx
src/components/tickoPages/tickoPage/CharIntroduce.jsx
src/pages/communityPages/postListPage/PostListPage.jsx
src/pages/startPages/ExFullPages.jsx
src/pages/startPages/ExplainPages/WelcomeEx.jsx
src/pages/startPages/StartPage.jsx
src/routes/BottomNavBarRoutes.jsx

close #67 
- 앱 시작 페이지 구현
- 추후 캘린더 페이지, 커뮤니티 페이지 추가할 예정입니다.
- 커뮤니티 페이지 추가 완료
- 슬라이드 기능 구현 완료

[UI] 앱 시작 페이지 제작

---

src/pages/startPages/ExFullPages.jsx
src/pages/startPages/StartPage.jsx
src/pages/stockcalendarPages/StockcalenPages.jsx
src/routes/BottomNavBarRoutes.jsx

close #92 
- 캘린더 페이지 설명 부분 추가
- 캘린더 페이지 내부에 하단 내브바, display 속성 추가
- 하단 내브바 라우팅 수정

[UI] 앱 시작 화면 내 캘린더 페이지 설명 추가

---

src/components/common/BackButton.jsx
src/components/common/UserProfile.jsx
src/components/communityPage/postWritePage/BottomBar.jsx
src/pages/communityPages/postWritePage/PostWritePage.jsx

[UI] 커뮤니티 페이지 텍스트 줄바꿈 문제 해결

---

src/components/information/CompanyInfo.jsx
src/components/information/CompanyList.jsx
src/pages/informationPages/Chart.jsx
src/pages/informationPages/DividendPage.jsx
src/pages/informationPages/Finance.jsx
src/pages/informationPages/InformationPage.jsx
src/pages/informationPages/List.jsx
src/pages/informationPages/NewsPage.jsx
src/pages/informationPages/Result.jsx
src/pages/informationPages/Volume.jsx
src/pages/myPages/FavoriteCompanies.jsx

close #95
정보 제공 페이지, 기업 목록, 마이페이지 관심 기업의 로고 삭제

ui: 기업 로고 삭제

---

src/pages/loginPage/LoginPage.jsx
src/pages/myPages/ScrapNews.jsx

1. 스크랩한 뉴스 페이지에 백엔드 연결 코드 추가
2. localStorage에 사용자 _id 추가

[FEAT] 백엔드 연결 코드 추가

---

src/components/stockcalendarPages/Stockcalendar.jsx
src/components/stockcalendarPages/StockcalendarSchedule.jsx
src/pages/portfolioPages/PortfolioMakePage.jsx
src/routes/BottomNavBarRoutes.jsx

close #19
배당락일 캘린더 페이지 좌우 균형 조정 
배당락일 캘린터 스케쥴 padding:15px 제거 
포트폴리오 제작 페이지 파일 추가

[UI] 배당락일 캘린더 수정 

---

src/components/common/SearchBar.jsx
src/pages/stockcalendarPages/StockcalenPages.jsx

close #102 
검색 API 연동 및 자동완성 기능 추가 했습니다.
자동완성은 최대 5개까지 뜨고, 
1. 자동완성된 종목을 눌렀을 때 2. 엔터를 눌렀을 때
검색결과가 표시됩니다.
만약 엔터를 눌렀을 때 검색 결과가 존재하지 않다면 경고창이 뜹니다.
현재 엔터를 누르고 검색결과가 없을 때 alert 창이 두번 뜨는 문제가 발생합니다.
추후에 수정하도록 하겠습니다.
navigate 링크 부분은 공백으로 처리했으니 수정하시면 될 것 같고 console.log() 부분은 삭제하지 말아주세요!
추후에 수정하도록 하겠습니다!

[FEAT] 검색 API 연동 및 자동완성 기능 추가
